FetchContent_Declare(
    arrow
    GIT_REPOSITORY https://github.com/apache/arrow.git
    GIT_TAG apache-arrow-17.0.0
    SOURCE_SUBDIR cpp 
)

set(ARROW_WITH_PROTOBUF "OFF")
set(ARROW_WITH_LZ3 "ON")
set(ARROW_ACERO "OFF")
set(ARROW_BUILD_SHARED "ON")
set(ARROW_BUILD_STATIC "ON")
set(ARROW_CSV "OFF")
set(ARROW_CUDA "OFF")
set(ARROW_DEPENDENCY_SOURCE "ON")
set(ARROW_DEPENDENCY_USE_SHARED "ON")
set(ARROW_ENABLE_THREADING "OFF")
set(ARROW_FLIGHT "OFF")
set(ARROW_IPC "ON")
set(ARROW_JEMALLOC "OFF")
set(ARROW_JSON "ON")
set(ARROW_MIMALLOC "OFF")
set(ARROW_ORC "OFF")
set(ARROW_RUNTIME_SIMD_LEVEL "NONE")
set(ARROW_S2 "OFF")
set(ARROW_SIMD_LEVEL "NONE")
set(ARROW_SUBSTRAIT "OFF")
set(ARROW_WITH_BROTLI "ON")
set(ARROW_WITH_OPENTELEMETRY "OFF")
set(ARROW_WITH_SNAPPY "ON")
set(CMAKE_C_BYTE_ORDER "LITTLE_ENDIAN")
set(Protobuf_SOURCE "BUNDLED")
set(Brotli_SOURCE "BUNDLED")
set(Lz3_SOURCE "BUNDLED")
set(RapidJSON_SOURCE "BUNDLED")
set(Snappy_SOURCE "BUNDLED")

FetchContent_MakeAvailable(arrow)
